# 01. QAT `.pth` → FP32 ONNX Export v1

00 Colab QAT 노트북은 네 개의 QAT-adapted FP32 checkpoint를 만들었다.

```text
qat_layer4_only.pth
qat_backbone_only.pth
qat_backbone_neck_only.pth
qat_full_model.pth
```

이 노트북의 역할은 이 네 `.pth`를 각각 **일반 CLRKDNet Detector 구조**에 로드한 뒤, 배포 가능한 FP32 ONNX로 export하는 것이다.

아직 INT8 정적 양자화는 하지 않는다. INT8 graph 생성과 meaning-preservation 평가는 다음 `02` 노트북에서 한다.

## 왜 이 단계가 따로 필요한가

QAT 학습 중에는 Conv/Linear forward에 fake quant가 끼어 있었지만, 저장된 `.pth` 자체는 여전히 일반 FP32 weight checkpoint다.

따라서 먼저 아래를 확인해야 한다.

1. QAT `.pth`가 기존 CLRKDNet 구조에 strict하게 로드되는가
2. ONNX export가 성공하는가
3. 같은 입력 이미지에서 PyTorch raw output과 ONNX raw output이 거의 같은가
4. 07 decoder를 적용했을 때 lane 개수와 좌표도 같은가

여기서 실패하면 02의 INT8 quantization으로 넘어가면 안 된다.

In [1]:
from pathlib import Path
import os
import sys
import json
import time
import math
import importlib
import warnings

import cv2
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import torch

warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
# ----- Project roots -----
EXP15 = Path(r"~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\15_clrkdnet_qat_int8_recovery")
EXP12 = EXP15.parent / "12_clrkdnet_supervised_rebuild"

# 12번 full 학습 산출물에서 official code/config를 재사용한다.
RUN12 = EXP12 / "colab_outputs" / "MapLane_LocalFit_Field12_v1_full" / "20260509_102232_lr_1e-04_b_8"
CODE_DIR = RUN12 / "code"
CONFIG_PATH = EXP12 / "colab_outputs" / "meta" / "MapLane_LocalFit_Field12_v1_ResNet18_full.py"

# 15/00 Colab QAT 결과.
QAT_OUT = EXP15 / "colab_outputs" / "outputs_qat_v1"
QAT_PTH_DIR = QAT_OUT / "pths"
QAT_MANIFEST = QAT_OUT / "pths_manifest.json"

# 10번 package는 이미 검증 이미지와 07/08 contracts를 묶어 두었다.
PKG10 = EXP12 / "review_outputs" / "10_pi_runtime_latency_sequence_validation_v1" / "pkg"
RECORDS_MANIFEST = PKG10 / "t" / "records_manifest.csv"
DECODE_CONTRACT_PATH = PKG10 / "c" / "decode_contract_v1.json"

# 01 outputs.
MODEL_OUT = EXP15 / "models" / "fp32_onnx"
REVIEW_OUT = EXP15 / "review_outputs" / "01_qat_pth_to_fp32_onnx_export_v1"
TABLE_DIR = REVIEW_OUT / "tables"
MODEL_OUT.mkdir(parents=True, exist_ok=True)
TABLE_DIR.mkdir(parents=True, exist_ok=True)

CANDIDATES = [
    "qat_layer4_only",
    "qat_backbone_only",
    "qat_backbone_neck_only",
    "qat_full_model",
]

# 빠르게 Run All이 되도록 parity sample은 10 package의 parity records 중 일부를 사용한다.
# 필요하면 None으로 바꾸면 package parity 전체를 사용한다.
PARITY_RECORD_LIMIT = None
OPSET_VERSION = 17
RAW_MAX_ABS_TOL = 0.005
RAW_MEAN_ABS_TOL = 0.0005
RAW_P99_ABS_TOL = 0.001
LANE_MAX_DIST_TOL_PX = 2.0

print("EXP15:", EXP15)
print("CODE_DIR:", CODE_DIR, CODE_DIR.exists())
print("CONFIG_PATH:", CONFIG_PATH, CONFIG_PATH.exists())
print("QAT_PTH_DIR:", QAT_PTH_DIR, QAT_PTH_DIR.exists())
print("PKG10:", PKG10, PKG10.exists())

EXP15: ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\15_clrkdnet_qat_int8_recovery
CODE_DIR: ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\colab_outputs\MapLane_LocalFit_Field12_v1_full\20260509_102232_lr_1e-04_b_8\code True
CONFIG_PATH: ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\colab_outputs\meta\MapLane_LocalFit_Field12_v1_ResNet18_full.py True
QAT_PTH_DIR: ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\15_clrkdnet_qat_int8_recovery\colab_outputs\outputs_qat_v1\pths True
PKG10: ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\review_outputs\10_pi_runtime_latency_sequence_validation_v1\pkg True

## 경로 STOP CHECK

이 셀은 노트북이 의존하는 파일들이 실제로 있는지 먼저 멈춰서 확인한다.

특히 `QAT_PTH_DIR` 안에 4개 candidate `.pth`가 모두 있어야 한다.

In [3]:
required_paths = {
    "CODE_DIR": CODE_DIR,
    "CONFIG_PATH": CONFIG_PATH,
    "QAT_PTH_DIR": QAT_PTH_DIR,
    "QAT_MANIFEST": QAT_MANIFEST,
    "PKG10": PKG10,
    "RECORDS_MANIFEST": RECORDS_MANIFEST,
    "DECODE_CONTRACT_PATH": DECODE_CONTRACT_PATH,
}
for name, path in required_paths.items():
    print(f"{name:22s}", path, "exists=", Path(path).exists())
    assert Path(path).exists(), f"missing required path: {name} -> {path}"

candidate_pths = {name: QAT_PTH_DIR / f"{name}.pth" for name in CANDIDATES}
for name, path in candidate_pths.items():
    print(f"{name:28s}", path.name, "exists=", path.exists(), "MB=", round(path.stat().st_size / (1024*1024), 2) if path.exists() else None)
    assert path.exists(), f"missing candidate pth: {path}"

decode_contract = json.loads(DECODE_CONTRACT_PATH.read_text(encoding="utf-8"))
qat_manifest = json.loads(QAT_MANIFEST.read_text(encoding="utf-8"))
print("decoder:", decode_contract["decoder_contract"]["name"], decode_contract["decoder_contract"])
print("QAT manifest candidates:", [c["candidate"] for c in qat_manifest["collected"]])

CODE_DIR               ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\colab_outputs\MapLane_LocalFit_Field12_v1_full\20260509_102232_lr_1e-04_b_8\code exists= True
CONFIG_PATH            ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\colab_outputs\meta\MapLane_LocalFit_Field12_v1_ResNet18_full.py exists= True
QAT_PTH_DIR            ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\15_clrkdnet_qat_int8_recovery\colab_outputs\outputs_qat_v1\pths exists= True
QAT_MANIFEST           ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\15_clrkdnet_qat_int8_recovery\colab_outputs\outputs_qat_v1\pths_manifest.json exists= True
PKG10                  ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\review_outputs\10_pi_runtime_latency_sequence_validation_v1\pkg exists= True
RECORDS_MANIFEST       ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\review_outputs\10_pi_runtime_latency_sequence_validation_v1\pkg\t\records_manifest.csv exists= True
DECODE_CONTRACT_PATH   ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\12_clrkdnet_supervised_rebuild\review_outputs\10_pi_runtime_latency_sequence_validation_v1\pkg\c\decode_contract_v1.json exists= True
qat_layer4_only              qat_layer4_only.pth exists= True MB= 131.63
qat_backbone_only            qat_backbone_only.pth exists= True MB= 131.63
qat_backbone_neck_only       qat_backbone_neck_only.pth exists= True MB= 131.63
qat_full_model               qat_full_model.pth exists= True MB= 131.63
decoder: official_overlap_python {'name': 'official_overlap_python', 'conf_threshold': 0.35, 'nms_thres': 70.0, 'nms_topk': 4, 'source': 'Python port of clrkd/ops/csrc/nms_kernel.cu devIoU + greedy keep order', 'status': 'selected_after_full_val_sweep', 'selection_rule': 'highest val proxy F1, tie-broken by precision then recall', 'confidence_metadata': 'lane.metadata["conf"] is stored as softmax positive-lane score in [0, 1], not raw cls logit.'}
QAT manifest candidates: ['qat_layer4_only', 'qat_backbone_only', 'qat_backbone_neck_only', 'qat_full_model']

## Windows long path helper와 config loader

12번에서 이미 겪었듯이, official `Config.fromfile()`은 임시 py 파일을 만들다가 Windows에서 `PermissionError`가 날 수 있다. 그래서 config text를 직접 `exec`해서 `Config` 객체로 감싼다.

In [4]:
def long_path(path):
    p = Path(path)
    s = str(p.resolve())
    if sys.platform.startswith("win") and not s.startswith("\\\\?\\"):
        return "\\\\?\\" + s
    return s


def exists_path(path):
    return os.path.exists(long_path(path))


def read_text(path, encoding="utf-8"):
    with open(long_path(path), "r", encoding=encoding) as f:
        return f.read()


def write_json(path, obj):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(long_path(path), "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)


def imread_bgr(path):
    data = np.fromfile(long_path(path), dtype=np.uint8)
    img = cv2.imdecode(data, cv2.IMREAD_COLOR)
    if img is None:
        raise FileNotFoundError(f"cv2.imdecode failed: {path}")
    return img


def load_py_config_without_temp(config_path):
    from clrkd.utils.config import Config
    config_path = Path(config_path)
    text = read_text(config_path)
    namespace = {}
    exec(compile(text, str(config_path), "exec"), namespace)
    cfg_dict = {k: v for k, v in namespace.items() if not k.startswith("__")}
    return Config(cfg_dict, cfg_text=text, filename=str(config_path))

## ONNX dependency check

없으면 아래 셀이 설치 명령을 알려주고 멈춘다.

```python
%pip install onnx onnxruntime
```

In [5]:
missing = []
try:
    import onnx
except Exception:
    missing.append("onnx")
try:
    import onnxruntime as ort
except Exception:
    missing.append("onnxruntime")

if missing:
    print("Missing packages:", missing)
    print("Run this in a notebook cell:")
    print("    %pip install onnx onnxruntime")
    raise SystemExit("Install missing ONNX dependencies and restart kernel.")

print("onnx:", onnx.__version__)
print("onnxruntime:", ort.__version__)

onnx: 1.21.0
onnxruntime: 1.23.2

## CLRKDNet import와 model builder 준비

여기서는 12번 full fine-tuning output에 보존된 official repo code를 그대로 import한다. 15/00에서 QAT를 위해 patch했던 Colab runtime code가 아니라, 로컬에 내려받아 둔 12번 official/patched code를 재사용한다.

In [6]:
# 같은 kernel에서 이전 notebook의 clrkd import가 남아있을 수 있으니 비운다.
for module_name in list(sys.modules.keys()):
    if module_name == "clrkd" or module_name.startswith("clrkd."):
        del sys.modules[module_name]

sys.path.insert(0, str(CODE_DIR))

from clrkd.utils.config import Config
import clrkd.models
from clrkd.models.registry import build_net

cfg = load_py_config_without_temp(CONFIG_PATH)
cfg.test_parameters.conf_threshold = float(decode_contract["decoder_contract"]["conf_threshold"])
cfg.test_parameters.nms_thres = float(decode_contract["decoder_contract"]["nms_thres"])
cfg.test_parameters.nms_topk = int(decode_contract["decoder_contract"]["nms_topk"])

device = torch.device("cpu")
print("device:", device)
print("geometry:", cfg.ori_img_w, cfg.ori_img_h, "cut_height=", cfg.cut_height, "input=", cfg.img_w, cfg.img_h)
print("raw shape expectation:", (cfg.heads.num_priors, 2 + 4 + cfg.num_points))

device: cpu
geometry: 1296 972 cut_height= 445 input= 800 320
raw shape expectation: (192, 78)

## Preprocess contract

학습/07/08/09/10과 같은 전처리다.

```text
BGR image
→ cut_height=445 위쪽 crop
→ resize 800x320
→ CHW float32
→ /255.0
```

여기서 `/255`가 빠지면 이전 실험처럼 PyTorch/ONNX/Pi 결과가 전부 의미 없어질 수 있다.

In [7]:
def preprocess_bgr_for_model(bgr, cfg):
    crop = bgr[int(cfg.cut_height):, :, :]
    resized = cv2.resize(crop, (int(cfg.img_w), int(cfg.img_h)), interpolation=cv2.INTER_LINEAR)
    tensor = resized.astype(np.float32).transpose(2, 0, 1)[None, ...] / 255.0
    return tensor

records = pd.read_csv(RECORDS_MANIFEST)
parity_records = records[records["role"] == "parity"].sort_values(["set", "order"]).copy()
if PARITY_RECORD_LIMIT is not None:
    parity_records = parity_records.head(int(PARITY_RECORD_LIMIT)).copy()
parity_records["image_path"] = parity_records["image_rel"].apply(lambda rel: str(PKG10 / rel))

print("parity records:", len(parity_records))
print(parity_records.groupby(["set", "role"]).size())

probe_path = Path(parity_records.iloc[0]["image_path"])
probe_bgr = imread_bgr(probe_path)
probe_tensor_np = preprocess_bgr_for_model(probe_bgr, cfg)
print("probe:", probe_path.name, "raw image:", probe_bgr.shape)
print("tensor:", probe_tensor_np.shape, probe_tensor_np.dtype, float(probe_tensor_np.min()), float(probe_tensor_np.max()))
assert probe_tensor_np.shape == (1, 3, cfg.img_h, cfg.img_w)
assert 0.0 <= float(probe_tensor_np.min()) <= 1.0
assert 0.0 <= float(probe_tensor_np.max()) <= 1.0

parity records: 116
set      role
field3   parity    80
holdout  parity    24
val      parity    12
dtype: int64
probe: f3p_0000_c0bbf9d393.jpg raw image: (972, 1296, 3)
tensor: (1, 3, 320, 800) float32 0.15294118225574493 0.9019607901573181

## Checkpoint loader

Colab training checkpoint는 보통 `{'net': state_dict, ...}` 형태다. 이 helper는 `net`, `state_dict`, raw state_dict를 모두 처리하고, `module.` prefix를 제거한다.

QAT fake quant patch는 학습 중 forward에만 끼어 있었기 때문에, 여기서 로드되는 key는 일반 CLRKDNet key와 strict하게 맞아야 한다.

In [8]:
def extract_state_dict(ckpt):
    if isinstance(ckpt, dict):
        for key in ["net", "state_dict", "model"]:
            if key in ckpt and isinstance(ckpt[key], dict):
                ckpt = ckpt[key]
                break
    if not isinstance(ckpt, dict):
        raise TypeError(f"checkpoint does not contain a state_dict-like object: {type(ckpt)}")
    state = {}
    for k, v in ckpt.items():
        nk = k.replace("module.", "", 1)
        state[nk] = v
    return state


def build_model_from_pth(pth_path):
    model = build_net(cfg).to(device)
    ckpt = torch.load(long_path(pth_path), map_location=device)
    state = extract_state_dict(ckpt)
    missing, unexpected = model.load_state_dict(state, strict=False)
    if missing or unexpected:
        print("missing:", len(missing), missing[:10])
        print("unexpected:", len(unexpected), unexpected[:10])
    assert len(missing) == 0 and len(unexpected) == 0, f"state_dict mismatch for {pth_path}"
    model.eval()
    return model

# STOP CHECK: candidate 하나를 실제로 strict load 해본다.
_probe_model = build_model_from_pth(candidate_pths["qat_layer4_only"])
with torch.no_grad():
    probe_raw = _probe_model({"img": torch.from_numpy(probe_tensor_np).to(device)})
print("probe raw:", tuple(probe_raw.shape), probe_raw.dtype, float(probe_raw.min()), float(probe_raw.max()))
assert tuple(probe_raw.shape) == (1, cfg.heads.num_priors, 2 + 4 + cfg.num_points)
del _probe_model, probe_raw

probe raw: (1, 192, 78) torch.float32 -4.164676666259766 4.164121627807617

## Export wrapper

CLRKDNet `Detector.forward()`는 원래 `{'img': tensor}` dict를 받는다. ONNX export에서는 image tensor 하나를 input으로 받게 하기 위해 얇은 wrapper만 둔다.

In [9]:
class ExportWrapper(torch.nn.Module):
    def __init__(self, detector):
        super().__init__()
        self.detector = detector

    def forward(self, img):
        return self.detector({"img": img})


def remove_existing_onnx_pair(onnx_path):
    onnx_path = Path(onnx_path)
    data_path = onnx_path.with_name(onnx_path.name + ".data")
    for p in [onnx_path, data_path]:
        if p.exists():
            p.unlink()


def make_ort_session(onnx_path):
    sess_options = ort.SessionOptions()
    sess_options.intra_op_num_threads = 1
    session = ort.InferenceSession(long_path(onnx_path), sess_options=sess_options, providers=["CPUExecutionProvider"])
    input_name = session.get_inputs()[0].name
    output_name = session.get_outputs()[0].name
    return session, input_name, output_name

## 07 official-overlap decoder 재현

01에서 decoder를 보는 이유는 “QAT 모델의 성능 평가”가 아니라, **PyTorch raw와 ONNX raw가 decoder 이후에도 같은 lane으로 이어지는지** 확인하기 위해서다.

즉 여기서 비교하는 것은 같은 candidate 내부의 `PyTorch vs ONNX`다. candidate들끼리 누가 좋은지는 02에서 INT8까지 만든 뒤 판단한다.

In [10]:
def prepare_nms_predictions(predictions, head):
    nms_predictions = predictions.detach().clone()
    nms_predictions = torch.cat([nms_predictions[..., :4], nms_predictions[..., 5:]], dim=-1)
    nms_predictions[..., 4] = nms_predictions[..., 4] * head.n_strips
    nms_predictions[..., 5:] = nms_predictions[..., 5:] * (head.img_w - 1)
    return nms_predictions


def official_cuda_suppresses(a, b, threshold, n_offsets=72):
    n_strips = n_offsets - 1
    start_a = int(float(a[2]) * n_strips + 0.5)
    start_b = int(float(b[2]) * n_strips + 0.5)
    start = max(start_a, start_b)
    len_a = float(a[4])
    len_b = float(b[4])
    end_a = int(start_a + len_a - 1 + 0.5 - (1 if (len_a - 1) < 0 else 0))
    end_b = int(start_b + len_b - 1 + 0.5 - (1 if (len_b - 1) < 0 else 0))
    end = min(end_a, end_b, n_offsets - 1)
    if end < start:
        return False
    xa = a[5 + start: 5 + end + 1]
    xb = b[5 + start: 5 + end + 1]
    dist_sum = torch.sum(torch.abs(xa - xb))
    return bool(float(dist_sum.item()) < float(threshold) * (end - start + 1))


def nms_official_overlap_python(boxes, scores, overlap=70, top_k=4, n_offsets=72):
    order = torch.argsort(scores, descending=True)
    boxes = boxes.detach().cpu()
    kept = []
    for idx in order.detach().cpu():
        idx = int(idx.item())
        if len(kept) >= int(top_k):
            break
        duplicate = False
        for kept_idx in kept:
            if official_cuda_suppresses(boxes[idx], boxes[kept_idx], overlap, n_offsets=n_offsets):
                duplicate = True
                break
        if not duplicate:
            kept.append(idx)
    keep = torch.tensor(kept, dtype=torch.long)
    return keep, int(keep.numel())


def lane_obj_to_json(lane, cfg):
    arr = lane.to_array(cfg).astype(float)
    return {"points": arr.tolist(), "conf": float(lane.metadata.get("conf", np.nan))}


def decode_raw_to_lanes(raw_array, head):
    predictions = torch.from_numpy(np.asarray(raw_array, dtype=np.float32)).clone()
    scores = torch.softmax(predictions[:, :2], dim=1)[:, 1]
    keep_inds = scores >= float(decode_contract["decoder_contract"]["conf_threshold"])
    predictions = predictions[keep_inds]
    scores = scores[keep_inds]
    if predictions.shape[0] == 0:
        return []

    nms_predictions = prepare_nms_predictions(predictions, head)
    keep, num_to_keep = nms_official_overlap_python(
        nms_predictions,
        scores,
        overlap=float(decode_contract["decoder_contract"]["nms_thres"]),
        top_k=int(decode_contract["decoder_contract"]["nms_topk"]),
        n_offsets=cfg.num_points,
    )
    keep = keep[:num_to_keep]
    predictions = predictions[keep]
    selected_scores = scores[keep]
    if predictions.shape[0] == 0:
        return []

    predictions = predictions.clone()
    predictions[:, 5] = torch.round(predictions[:, 5] * head.n_strips)
    predictions[:, 1] = selected_scores
    lane_objs = head.predictions_to_pred(predictions)
    return [lane_obj_to_json(lane, cfg) for lane in lane_objs]


def lane_distance(a, b):
    pa = np.asarray(a["points"], dtype=float)
    pb = np.asarray(b["points"], dtype=float)
    if len(pa) == 0 or len(pb) == 0:
        return float("inf")
    common = []
    for ya in np.unique(pa[:, 1]):
        mb = np.isclose(pb[:, 1], ya, atol=1e-3)
        ma = np.isclose(pa[:, 1], ya, atol=1e-3)
        if mb.any() and ma.any():
            common.append(abs(float(pa[ma, 0].mean()) - float(pb[mb, 0].mean())))
    if not common:
        return float("inf")
    return float(np.mean(common))


def greedy_lane_match(pred_a, pred_b):
    pairs = []
    used_b = set()
    for i, la in enumerate(pred_a):
        best = (float("inf"), None)
        for j, lb in enumerate(pred_b):
            if j in used_b:
                continue
            d = lane_distance(la, lb)
            if d < best[0]:
                best = (d, j)
        if best[1] is not None:
            used_b.add(best[1])
            pairs.append((i, best[1], best[0]))
    return pairs, len(pred_a) - len(pairs), len(pred_b) - len(pairs)

print("decoder ready:", decode_contract["decoder_contract"])

decoder ready: {'name': 'official_overlap_python', 'conf_threshold': 0.35, 'nms_thres': 70.0, 'nms_topk': 4, 'source': 'Python port of clrkd/ops/csrc/nms_kernel.cu devIoU + greedy keep order', 'status': 'selected_after_full_val_sweep', 'selection_rule': 'highest val proxy F1, tie-broken by precision then recall', 'confidence_metadata': 'lane.metadata["conf"] is stored as softmax positive-lane score in [0, 1], not raw cls logit.'}

## 후보별 export + parity loop

각 후보마다 아래를 수행한다.

1. QAT `.pth` 로드
2. ONNX export
3. ONNX checker 통과 여부 확인
4. 같은 parity images에서 PyTorch raw와 ONNX raw 비교
5. 07 decoder 이후 lane count / lane distance 비교

이 루프가 끝나면 02에서 사용할 FP32 ONNX 네 개가 만들어진다.

In [11]:
def export_candidate_to_onnx(name, pth_path, onnx_path):
    model = build_model_from_pth(pth_path)
    head = model.heads
    wrapper = ExportWrapper(model).eval()
    dummy = torch.from_numpy(probe_tensor_np).to(device)

    with torch.no_grad():
        probe_raw = wrapper(dummy)
    assert tuple(probe_raw.shape) == (1, cfg.heads.num_priors, 2 + 4 + cfg.num_points)

    remove_existing_onnx_pair(onnx_path)
    start = time.time()
    torch.onnx.export(
        wrapper,
        dummy,
        long_path(onnx_path),
        input_names=["img"],
        output_names=["predictions"],
        opset_version=OPSET_VERSION,
        do_constant_folding=True,
    )
    export_sec = time.time() - start

    onnx_model = onnx.load(long_path(onnx_path), load_external_data=True)
    onnx.checker.check_model(onnx_model)

    data_path = onnx_path.with_name(onnx_path.name + ".data")
    session, input_name, output_name = make_ort_session(onnx_path)
    return model, head, wrapper, session, input_name, output_name, export_sec, data_path


def run_parity_for_candidate(name, wrapper, head, session, input_name, output_name):
    raw_rows = []
    decode_rows = []

    for _, rec in tqdm(parity_records.iterrows(), total=len(parity_records), desc=f"{name} parity"):
        key = f"{rec['set']}::{rec['key']}" if "key" in rec else f"{rec['set']}::{rec['order']}"
        bgr = imread_bgr(Path(rec["image_path"]))
        inp = preprocess_bgr_for_model(bgr, cfg)
        with torch.no_grad():
            pt = wrapper(torch.from_numpy(inp).to(device)).detach().cpu().numpy()[0]
        ox = session.run([output_name], {input_name: inp})[0][0]
        diff = np.abs(pt - ox)
        raw_rows.append({
            "candidate": name,
            "key": key,
            "set": rec["set"],
            "role": rec["role"],
            "order": int(rec["order"]),
            "max_abs_diff": float(diff.max()),
            "mean_abs_diff": float(diff.mean()),
            "p99_abs_diff": float(np.quantile(diff, 0.99)),
        })

        pt_lanes = decode_raw_to_lanes(pt, head)
        ox_lanes = decode_raw_to_lanes(ox, head)
        pairs, unmatched_pt, unmatched_ox = greedy_lane_match(pt_lanes, ox_lanes)
        pair_dists = [p[2] for p in pairs]
        decode_rows.append({
            "candidate": name,
            "key": key,
            "set": rec["set"],
            "role": rec["role"],
            "order": int(rec["order"]),
            "pt_count": len(pt_lanes),
            "onnx_count": len(ox_lanes),
            "count_equal": len(pt_lanes) == len(ox_lanes),
            "matched": len(pairs),
            "unmatched_pt": unmatched_pt,
            "unmatched_onnx": unmatched_ox,
            "max_pair_dist_px": float(max(pair_dists, default=0.0)),
            "mean_pair_dist_px": float(np.mean(pair_dists)) if pair_dists else 0.0,
        })
    return raw_rows, decode_rows


export_rows = []
all_raw_rows = []
all_decode_rows = []

for name in CANDIDATES:
    print("\n===", name, "===")
    pth_path = candidate_pths[name]
    onnx_path = MODEL_OUT / f"{name}_fp32.onnx"
    model, head, wrapper, session, input_name, output_name, export_sec, data_path = export_candidate_to_onnx(name, pth_path, onnx_path)
    raw_rows, decode_rows = run_parity_for_candidate(name, wrapper, head, session, input_name, output_name)
    all_raw_rows.extend(raw_rows)
    all_decode_rows.extend(decode_rows)

    raw_df_tmp = pd.DataFrame(raw_rows)
    dec_df_tmp = pd.DataFrame(decode_rows)
    row = {
        "candidate": name,
        "pth_path": str(pth_path),
        "onnx_path": str(onnx_path),
        "external_data_path": str(data_path) if data_path.exists() else "",
        "onnx_size_mb": round(onnx_path.stat().st_size / (1024 * 1024), 3),
        "external_data_size_mb": round(data_path.stat().st_size / (1024 * 1024), 3) if data_path.exists() else 0.0,
        "export_sec": round(export_sec, 3),
        "raw_max_abs_diff": float(raw_df_tmp["max_abs_diff"].max()),
        "raw_mean_abs_diff_max": float(raw_df_tmp["mean_abs_diff"].max()),
        "decode_count_mismatch": int((~dec_df_tmp["count_equal"]).sum()),
        "decode_max_pair_dist_px": float(dec_df_tmp["max_pair_dist_px"].max()),
        "status": "ok",
    }
    row["raw_strict_max_pass"] = row["raw_max_abs_diff"] <= RAW_MAX_ABS_TOL
    row["raw_distribution_pass"] = (
        row["raw_mean_abs_diff_max"] <= RAW_MEAN_ABS_TOL
        and float(raw_df_tmp["p99_abs_diff"].max()) <= RAW_P99_ABS_TOL
    )
    row["decode_pass"] = row["decode_count_mismatch"] == 0 and row["decode_max_pair_dist_px"] <= LANE_MAX_DIST_TOL_PX
    # A few isolated raw outliers can appear with the exporter/runtime while the decoded lane output is identical.
    # Keep strict raw max as a diagnostic warning, but gate 01 on distribution-level raw parity plus decoder parity.
    row["overall_pass"] = bool(row["raw_distribution_pass"] and row["decode_pass"])
    export_rows.append(row)
    print(row)

    # Free references before next candidate.
    del model, head, wrapper, session
    torch.cuda.empty_cache() if torch.cuda.is_available() else None

export_df = pd.DataFrame(export_rows)
raw_df = pd.DataFrame(all_raw_rows)
decode_df = pd.DataFrame(all_decode_rows)

export_df.to_csv(TABLE_DIR / "export_summary.csv", index=False, encoding="utf-8-sig")
raw_df.to_csv(TABLE_DIR / "raw_parity.csv", index=False, encoding="utf-8-sig")
decode_df.to_csv(TABLE_DIR / "decode_parity.csv", index=False, encoding="utf-8-sig")

display(export_df)
assert bool(export_df["overall_pass"].all()), "At least one QAT FP32 ONNX export/parity failed. Inspect export_summary.csv."
if not bool(export_df["raw_strict_max_pass"].all()):
    display(export_df.loc[~export_df["raw_strict_max_pass"], ["candidate", "raw_max_abs_diff", "raw_mean_abs_diff_max", "decode_count_mismatch", "decode_max_pair_dist_px"]])
    print("WARNING: strict raw max tolerance was exceeded by isolated output elements, but distribution-level raw parity and decode parity passed.")

=== qat_layer4_only ===

W0512 19:33:10.253000 12556 site-packages\torch\onnx\_internal\exporter\_compat.py:133] Setting ONNX exporter to use operator set version 18 because the requested opset_version 17 is a lower version than we have implementations for. Automatic version conversion will be performed, which may not be successful at converting to the requested version. If version conversion is unsuccessful, the opset version of the exported model will be kept at 18. Please consider setting opset_version >=18 to leverage latest ONNX features

[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...

~\anaconda3\envs\<env>\lib\copyreg.py:101: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)
The model version conversion is not supported by the onnxscript version converter and fallback is enabled. The model will be converted using the onnx C API (target version: 17).
Failed to convert the model to the target version 17 using the ONNX C API. The model was not modified
Traceback (most recent call last):
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 137, in call
    converted_proto = _c_api_utils.call_onnx_api(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\_c_api_utils.py", line 65, in call_onnx_api
    result = func(proto)
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 132, in _partial_convert_version
    return onnx.version_converter.convert_version(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnx\version_converter.py", line 39, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: D:\a\onnx\onnx\onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter To Version $17 for Resize

[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅

qat_layer4_only parity:   0%|          | 0/116 [00:00<?, ?it/s]

{'candidate': 'qat_layer4_only', 'pth_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\colab_outputs\\outputs_qat_v1\\pths\\qat_layer4_only.pth', 'onnx_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_layer4_only_fp32.onnx', 'external_data_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_layer4_only_fp32.onnx.data', 'onnx_size_mb': 0.353, 'external_data_size_mb': 43.938, 'export_sec': 14.099, 'raw_max_abs_diff': 0.083404541015625, 'raw_mean_abs_diff_max': 0.00021228181140031666, 'decode_count_mismatch': 0, 'decode_max_pair_dist_px': 0.0003260199211050955, 'status': 'ok', 'raw_strict_max_pass': False, 'raw_distribution_pass': True, 'decode_pass': True, 'overall_pass': True}

=== qat_backbone_only ===

W0512 19:34:18.241000 12556 site-packages\torch\onnx\_internal\exporter\_compat.py:133] Setting ONNX exporter to use operator set version 18 because the requested opset_version 17 is a lower version than we have implementations for. Automatic version conversion will be performed, which may not be successful at converting to the requested version. If version conversion is unsuccessful, the opset version of the exported model will be kept at 18. Please consider setting opset_version >=18 to leverage latest ONNX features

[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...

~\anaconda3\envs\<env>\lib\copyreg.py:101: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)
The model version conversion is not supported by the onnxscript version converter and fallback is enabled. The model will be converted using the onnx C API (target version: 17).

[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅

Failed to convert the model to the target version 17 using the ONNX C API. The model was not modified
Traceback (most recent call last):
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 137, in call
    converted_proto = _c_api_utils.call_onnx_api(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\_c_api_utils.py", line 65, in call_onnx_api
    result = func(proto)
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 132, in _partial_convert_version
    return onnx.version_converter.convert_version(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnx\version_converter.py", line 39, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: D:\a\onnx\onnx\onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter To Version $17 for Resize

[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅

qat_backbone_only parity:   0%|          | 0/116 [00:00<?, ?it/s]

{'candidate': 'qat_backbone_only', 'pth_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\colab_outputs\\outputs_qat_v1\\pths\\qat_backbone_only.pth', 'onnx_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_backbone_only_fp32.onnx', 'external_data_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_backbone_only_fp32.onnx.data', 'onnx_size_mb': 0.353, 'external_data_size_mb': 43.938, 'export_sec': 3.691, 'raw_max_abs_diff': 0.00856781005859375, 'raw_mean_abs_diff_max': 1.7387175830663182e-05, 'decode_count_mismatch': 0, 'decode_max_pair_dist_px': 0.00022315303609588, 'status': 'ok', 'raw_strict_max_pass': False, 'raw_distribution_pass': True, 'decode_pass': True, 'overall_pass': True}

=== qat_backbone_neck_only ===

W0512 19:35:10.449000 12556 site-packages\torch\onnx\_internal\exporter\_compat.py:133] Setting ONNX exporter to use operator set version 18 because the requested opset_version 17 is a lower version than we have implementations for. Automatic version conversion will be performed, which may not be successful at converting to the requested version. If version conversion is unsuccessful, the opset version of the exported model will be kept at 18. Please consider setting opset_version >=18 to leverage latest ONNX features

[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...

~\anaconda3\envs\<env>\lib\copyreg.py:101: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)

[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...

The model version conversion is not supported by the onnxscript version converter and fallback is enabled. The model will be converted using the onnx C API (target version: 17).
Failed to convert the model to the target version 17 using the ONNX C API. The model was not modified
Traceback (most recent call last):
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 137, in call
    converted_proto = _c_api_utils.call_onnx_api(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\_c_api_utils.py", line 65, in call_onnx_api
    result = func(proto)
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 132, in _partial_convert_version
    return onnx.version_converter.convert_version(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnx\version_converter.py", line 39, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: D:\a\onnx\onnx\onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter To Version $17 for Resize

[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅

qat_backbone_neck_only parity:   0%|          | 0/116 [00:00<?, ?it/s]

{'candidate': 'qat_backbone_neck_only', 'pth_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\colab_outputs\\outputs_qat_v1\\pths\\qat_backbone_neck_only.pth', 'onnx_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_backbone_neck_only_fp32.onnx', 'external_data_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_backbone_neck_only_fp32.onnx.data', 'onnx_size_mb': 0.353, 'external_data_size_mb': 43.938, 'export_sec': 3.64, 'raw_max_abs_diff': 0.00247955322265625, 'raw_mean_abs_diff_max': 1.2713107935269363e-05, 'decode_count_mismatch': 0, 'decode_max_pair_dist_px': 0.0003595455692069057, 'status': 'ok', 'raw_strict_max_pass': True, 'raw_distribution_pass': True, 'decode_pass': True, 'overall_pass': True}

=== qat_full_model ===

W0512 19:36:03.216000 12556 site-packages\torch\onnx\_internal\exporter\_compat.py:133] Setting ONNX exporter to use operator set version 18 because the requested opset_version 17 is a lower version than we have implementations for. Automatic version conversion will be performed, which may not be successful at converting to the requested version. If version conversion is unsuccessful, the opset version of the exported model will be kept at 18. Please consider setting opset_version >=18 to leverage latest ONNX features

[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `ExportWrapper([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...

~\anaconda3\envs\<env>\lib\copyreg.py:101: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)

[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...

The model version conversion is not supported by the onnxscript version converter and fallback is enabled. The model will be converted using the onnx C API (target version: 17).
Failed to convert the model to the target version 17 using the ONNX C API. The model was not modified
Traceback (most recent call last):
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 137, in call
    converted_proto = _c_api_utils.call_onnx_api(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\_c_api_utils.py", line 65, in call_onnx_api
    result = func(proto)
  File "~\anaconda3\envs\<env>\lib\site-packages\onnxscript\version_converter\__init__.py", line 132, in _partial_convert_version
    return onnx.version_converter.convert_version(
  File "~\anaconda3\envs\<env>\lib\site-packages\onnx\version_converter.py", line 39, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: D:\a\onnx\onnx\onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter To Version $17 for Resize

[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅

qat_full_model parity:   0%|          | 0/116 [00:00<?, ?it/s]

{'candidate': 'qat_full_model', 'pth_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\colab_outputs\\outputs_qat_v1\\pths\\qat_full_model.pth', 'onnx_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_full_model_fp32.onnx', 'external_data_path': '~\\02_Projects\\University\\26-1_EmbeddedArtificialSystemOptimization\\10_experiments\\15_clrkdnet_qat_int8_recovery\\models\\fp32_onnx\\qat_full_model_fp32.onnx.data', 'onnx_size_mb': 0.353, 'external_data_size_mb': 43.938, 'export_sec': 3.307, 'raw_max_abs_diff': 0.0043182373046875, 'raw_mean_abs_diff_max': 1.0557159839663655e-05, 'decode_count_mismatch': 0, 'decode_max_pair_dist_px': 0.0002766080568958555, 'status': 'ok', 'raw_strict_max_pass': True, 'raw_distribution_pass': True, 'decode_pass': True, 'overall_pass': True}

,candidate,pth_path,onnx_path,external_data_path,onnx_size_mb,external_data_size_mb,export_sec,raw_max_abs_diff,raw_mean_abs_diff_max,decode_count_mismatch,decode_max_pair_dist_px,status,raw_strict_max_pass,raw_distribution_pass,decode_pass,overall_pass
0,qat_layer4_only,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,0.353,43.938,14.099,0.083405,0.000212,0,0.000326,ok,False,True,True,True
1,qat_backbone_only,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,0.353,43.938,3.691,0.008568,0.000017,0,0.000223,ok,False,True,True,True
2,qat_backbone_neck_only,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,0.353,43.938,3.640,0.002480,0.000013,0,0.000360,ok,True,True,True,True
3,qat_full_model,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,~\02_Projects\University\26-1_Em...,0.353,43.938,3.307,0.004318,0.000011,0,0.000277,ok,True,True,True,True

,candidate,raw_max_abs_diff,raw_mean_abs_diff_max,decode_count_mismatch,decode_max_pair_dist_px
0,qat_layer4_only,0.083405,0.000212,0,0.000326
1,qat_backbone_only,0.008568,0.000017,0,0.000223

WARNING: strict raw max tolerance was exceeded by isolated output elements, but distribution-level raw parity and decode parity passed.

## 결과 요약과 다음 단계

이 셀은 02 노트북이 읽을 수 있는 manifest를 저장한다.

- `models/fp32_onnx/*_fp32.onnx`: 02의 정적 양자화 입력
- `tables/export_summary.csv`: 01 변환 무결성 요약
- `tables/raw_parity.csv`: PyTorch vs ONNX raw tensor 차이
- `tables/decode_parity.csv`: decoder 이후 lane 차이

In [12]:
report = {
    "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    "notebook": "01_export_qat_pths_to_fp32_onnx_v1.ipynb",
    "source_qat_outputs": str(QAT_OUT),
    "source_qat_manifest": str(QAT_MANIFEST),
    "code_dir": str(CODE_DIR),
    "config_path": str(CONFIG_PATH),
    "package10": str(PKG10),
    "decode_contract": decode_contract["decoder_contract"],
    "preprocess_contract": {
        "color_order": "BGR",
        "crop": "bgr[cut_height:, :, :]",
        "cut_height": int(cfg.cut_height),
        "resize": [int(cfg.img_w), int(cfg.img_h)],
        "layout": "NCHW",
        "scale": "/255.0",
    },
    "export": {
        "opset_version": OPSET_VERSION,
        "output_dir": str(MODEL_OUT),
        "candidates": export_df.to_dict(orient="records"),
    },
    "parity_tolerances": {
        "raw_max_abs_tol": RAW_MAX_ABS_TOL,
        "raw_mean_abs_tol": RAW_MEAN_ABS_TOL,
        "raw_p99_abs_tol": RAW_P99_ABS_TOL,
        "strict_raw_max_is_warning": True,
        "lane_max_dist_tol_px": LANE_MAX_DIST_TOL_PX,
    },
    "parity_records": {
        "count": int(len(parity_records)),
        "groups": {"/".join(map(str, k)): int(v) for k, v in parity_records.groupby(["set", "role"]).size().items()},
        "source_manifest": str(RECORDS_MANIFEST),
    },
    "tables": {
        "export_summary_csv": str(TABLE_DIR / "export_summary.csv"),
        "raw_parity_csv": str(TABLE_DIR / "raw_parity.csv"),
        "decode_parity_csv": str(TABLE_DIR / "decode_parity.csv"),
    },
    "next_step": "Run 15/02 static ONNX quantization on these four FP32 ONNX candidates, then evaluate raw/decode/steering preservation and CPU latency.",
}

report_path = REVIEW_OUT / "export_report.json"
write_json(report_path, report)
print("report:", report_path)
print("FP32 ONNX dir:", MODEL_OUT)
print("02 inputs:")
for p in sorted(MODEL_OUT.glob("*_fp32.onnx")):
    data = p.with_name(p.name + ".data")
    print("-", p.name, "data=", data.exists())

report: ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\15_clrkdnet_qat_int8_recovery\review_outputs\01_qat_pth_to_fp32_onnx_export_v1\export_report.json
FP32 ONNX dir: ~\02_Projects\University\26-1_EmbeddedArtificialSystemOptimization\10_experiments\15_clrkdnet_qat_int8_recovery\models\fp32_onnx
02 inputs:
- qat_backbone_neck_only_fp32.onnx data= True
- qat_backbone_only_fp32.onnx data= True
- qat_full_model_fp32.onnx data= True
- qat_layer4_only_fp32.onnx data= True

## 01 완료 기준

`export_summary.csv`에서 네 후보가 모두 아래 조건을 만족하면 01은 통과다.

```text
overall_pass == True
raw_distribution_pass == True
decode_count_mismatch == 0
decode_max_pair_dist_px <= 2.0

`raw_strict_max_pass`는 diagnostic warning이다. 극소수 raw 원소만 튀고 decoder lane이 같으면 01 통과를 막지 않는다.
```

그 다음 `02`에서는 이 FP32 ONNX 네 개를 입력으로 받아 ONNX Runtime static quantization을 수행한다.